config/routes.rb
Rails.application.routes.draw do

  resources :evaluations
  devise_for :users
  root 'home#index'

  get 'home/index'

  resources :teams do
    resources :events
  end
  resources :people
  resources :semesters
  resources :disciplines
  resources :contact
  resources :reports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discipline.rb
class Discipline < ApplicationRecord
    validates :descricao , presence: true
    validates :cargaHoraria , presence: true
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /disciplines
  # GET /disciplines.json
  def index
     if params[:search]
          @disciplines = Discipline.where("lower(descricao) like ?", "%#{params[:search]}%".downcase)
      else
         @disciplines = Discipline.all
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:descricao, :codigo, :sigla, :cargaHoraria, :periodo)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :discipline_descricao %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, id: :discipline_codigo %>
  </div>

  <div class="field">
    <%= form.label :sigla %>
    <%= form.text_field :sigla, id: :discipline_sigla %>
  </div>

  <div class="field">
    <%= form.label :cargaHoraria %>
    <%= form.number_field :cargaHoraria, id: :discipline_cargaHoraria %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplines</h1>

<br>
<%= form_tag(disciplines_path, :method => :get) do %>
<%= text_field_tag 'search', nil, placeholder: 'Entre termo Descricao ...'   %>
<%= submit_tag "Pesquisar ..." %> 
<% end %> 
<br>



<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Codigo</th>
      <th>Sigla</th>
      <th>Cargahoraria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.descricao %></td>
        <td><%= discipline.codigo %></td>
        <td><%= discipline.sigla %></td>
        <td><%= discipline.cargaHoraria %></td>
        <td><%= link_to 'Show', discipline %></td>
        <% if current_user.person.coordenador? %>
          <td><%= link_to 'Edit', edit_discipline_path(discipline) %></td>
          <td><%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.person.coordenador? %>
  <%= link_to 'New Discipline', new_discipline_path %>
<%end%>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @discipline.descricao %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @discipline.codigo %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @discipline.sigla %>
</p>

<p>
  <strong>Cargahoraria:</strong>
  <%= @discipline.cargaHoraria %>
</p>


<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<%= link_to 'Back', disciplines_path %>