config/routes.rb
Rails.application.routes.draw do

  resources :evaluations
  devise_for :users
  root 'home#index'

  get 'home/index'

  resources :teams do
    resources :events
  end
  resources :people
  resources :semesters
  resources :disciplines
  resources :contact
  resources :reports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :events
    has_one :turma, class_name: "Team", inverse_of: "monitor", foreign_key: "monitor_id"
    validates :nome, presence: true,  length: { minimum: 3 }
    validates :matricula, presence: true, uniqueness: true
    validates :user , presence: true
    enum perfil: [:coordenador, :aluno]
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.user = current_user
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:nome, :matricula, :telefone, :perfil, :user_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :person_nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula, id: :person_matricula %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :person_telefone %>
  </div>

  <%if current_user.person.coordenador? %>
    <div class="field">
      <%= form.label :perfil %>
      <%= form.select(:perfil, Person.perfils.keys.map {|key| [key.humanize, key]},
        id: :person_perfil,  include_blank: true ) %>
    </div>
  <%else%>
  <div style="visibility:hidden" class="field">
    <%= form.label :perfil %>
    <%= form.select(:perfil, Person.perfils.keys.map {|key| [key.humanize, key]},
      id: :person_perfil,  include_blank: true, :selected=>Person.perfils.key(1) ) %>
  </div>
  <%end%>
  <div style="visibility:hidden" class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :person_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Telefone</th>
      <th>Perfil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.nome %></td>
        <td><%= person.matricula %></td>
        <td><%= person.telefone %></td>
        <td><%= person.perfil  %></td>
        <td><%= link_to 'Show', person %></td>
        <% if current_user.person.coordenador? || current_user.person.matricula == person.matricula %>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.person.coordenador? %>
  <%= link_to 'New Person', new_person_path %>
<% end %>

app/views/people/new.html.erb
<h1>Complete seu cadastro</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @person.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @person.matricula %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @person.telefone %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @person.perfil %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>