config/routes.rb
Rails.application.routes.draw do

  resources :evaluations
  devise_for :users
  root 'home#index'

  get 'home/index'

  resources :teams do
    resources :events
  end
  resources :people
  resources :semesters
  resources :disciplines
  resources :contact
  resources :reports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discipline.rb
class Discipline < ApplicationRecord
    validates :descricao , presence: true
    validates :cargaHoraria , presence: true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :people
  belongs_to :team

  has_many :evaluations

  def media
    media = 0.0
    evaluations.each {|e| media+=e.nota}
    media/evaluations.size
  end
end

app/models/person.rb
class Person < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :events
    has_one :turma, class_name: "Team", inverse_of: "monitor", foreign_key: "monitor_id"
    validates :nome, presence: true,  length: { minimum: 3 }
    validates :matricula, presence: true, uniqueness: true
    validates :user , presence: true
    enum perfil: [:coordenador, :aluno]
end

app/models/semester.rb
class Semester < ApplicationRecord
    def to_s
        "#{self.ano}/#{self.periodo}"
    end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :discipline
  belongs_to :semester
  belongs_to :monitor , class_name:"Person", foreign_key: "monitor_id", optional: true
  has_many :events
  #validates :discipline, uniqueness: true
  def descricao
    "#{discipline.descricao} - #{semester}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :person
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable #, :validatable
  validates :email , uniqueness: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teams = Team.all
    @chave = " ";
     if params[:search]
      @chave = params[:search]
    end

    # if params[:search]
    #   @people = Person.where("nome LIKE ?", "%"+params[:search]+"%")
    # else
    #   @people = nil
    # end
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show

    if params[:name] 
       if current_user.person.events.include? Event.find(params[:name])
        Event.find(params[:name]).people.delete(current_user.person)
        current_user.person.events.delete(Event.find(params[:name]))
       else
          current_user.person.events << Event.find(params[:name])
       end
    end

    @alunos = Person.aluno
    @events = @team.events
    @event = Event.new
    @event.team = @team
  end

  # GET /teams/new
  def new
    @team = Team.new
    @semesters = Semester.all
    @discliplines = Discipline.all
  end

  # GET /teams/1/edit
  def edit
    @semesters = Semester.all
    @discliplines = Discipline.all
  end

  # POST /teams 
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|         
      
      if( Team.where(discipline_id:team_params[:discipline_id], semester_id:team_params[:semester_id]).size > 0)
       format.html { redirect_to teams_path, notice: 'Já existe uma turma com essa disciplina para o semestre informado.' }
      else
        if @team.save
          format.html { redirect_to @team, notice: 'Team was successfully created.' }
          format.json { render :show, status: :created, location: @team }
        else
          format.html { render :new }
          format.json { render json: @team.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    id_semester = Team.find(params[:id]).semester.id
    respond_to do |format|
      if (Team.where("monitor_id = ? and semester_id = ? ", team_params[:monitor_id], id_semester).size > 0)
        format.html { redirect_to team_path, notice: 'Este monitor está alocado em uma disciplina'}
        format.json { render :show, status: :ok, location: @team }
      else
        if @team.update(team_params)
          format.html { redirect_to @team, notice: 'Team was successfully updated.' }
          format.json { render :show, status: :ok, location: @team }
        else
          format.html { render :edit }
          format.json { render json: @team.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:discipline_id, :semester_id, :editalAnexo, :monitor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monitoria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render partial: "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Monitoria</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= people_path %>">Usuários</a></li>
        <li><a href="<%= disciplines_path %>">Disciplinas</a></li>
        <li><a href="<%= semesters_path %>">Semestres</a></li>
        <li><a href="<%= teams_path%>">Turmas</a></li>
        <li><a href="<%= reports_path%>">Relatórios</a></li>
      </ul>
      <% if user_signed_in?%>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <!--%if current_user.person.nil?%-->
            <%=current_user.person.nome unless current_user.person.nil? %>
          <!--%end%-->
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %></li>
          </ul>
        </li>
      </ul>
      <%else%>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login" , new_user_session_path %></li>
        <li><%= link_to "Cadastrar" , new_user_registration_path %></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>