config/routes.rb
Rails.application.routes.draw do

  resources :evaluations
  devise_for :users
  root 'home#index'

  get 'home/index'

  resources :teams do
    resources :events
  end
  resources :people
  resources :semesters
  resources :disciplines
  resources :contact
  resources :reports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :people
  belongs_to :team

  has_many :evaluations

  def media
    media = 0.0
    evaluations.each {|e| media+=e.nota}
    media/evaluations.size
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :get_team

  def get_team
    @team = Team.find(params[:team_id])
  end

  # GET /events
  # GET /events.json
  def index
    if params[:team_id].nil?
      @events = Event.all
    else
      @events = @team.events
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.all
    if params[:status]
      temp = Event.find(@event.id)
      temp.update(status: true)
      current_user.person.events <<  temp
    end
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.team = @team
    @events = Event.all
  end

  # GET /events/1/edit
  def edit
    @events = Event.all
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    if current_user.person.turma
      if current_user.person.turma == @team
        @event.status = true
      end
    end
  
    @event.autor_id = current_user.id
    current_user.person.events <<  @event

    respond_to do |format|
      if @event.save
        format.html { redirect_to [@team,@event], notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@team,@event], notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to team_url(@team), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params_status
      params.require(:event).permit(:status)
    end

    def event_params
      params.require(:event).permit(:team_id, :inicio, :fim, :local, :descricao)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: [@team,event], local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, id: :event_team_id %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :event_descricao %>
  </div>

  <div class="field">
    <%= form.label :inicio %>
    <%= form.date_field :inicio, id: :event_inicio %>
  </div>

  <div class="field">
    <%= form.label :fim %>
    <%= form.date_field :fim, id: :event_fim %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local, id: :event_local %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Monitorias</h1>


<%= form_tag new_team_event_path(@team), :method => 'get' do %>
  <div class="form-group" id="btn_agendar">
        <button <%= submit_tag "Agendar monitoria" , :name => nil%>Agendar monitoria</button>
  </div>
<% end %>

  <%if @team.monitor != nil %>
    <%= form_tag contact_index_path, :method => 'get' do %>
      <div class="form-group" id="btn_contactar">
            <button <%= submit_tag "Contactar monitor" , :name => 'email' , value: @team.monitor.user.email %>Contactar monitor</button>
      </div>
    <% end %>
  <% end %>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Turma</th>
      <th scope="col">Data</th>
      <th scope="col">Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%= " Total de horas de monitoria: #{@events.size} " %>
  <tbody>

    <% @events.each do |event| %>
      <tr>
        <%if event.status %>
            <td><%= event.descricao %></td>
            <td><%= I18n.l(event.inicio) %></td>
            <td><%= event.local %></td>
            <td><%= link_to 'Show', team_event_path(@team,event) %></td>
            <% if current_user.person == event.team.monitor %>
              <td><%= link_to 'Edit', edit_team_event_path(@team,event) %></td>
              <td><%= link_to 'Destroy', [@team,event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
            <% if current_user.person.events.include? event %>
                <td><%= link_to 'Sair', :name => event.id %></td>
            <% else %>
              <td><%= link_to 'Participar', :name => event.id %></td>
            <% end %>
        <% elsif current_user.person.turma == @team or current_user.person.id == event.autor_id %>
              <td><%= event.descricao %></td>
              <td><%= I18n.l(event.inicio) %></td>
              <td><%= event.local %></td>

              <td><%= link_to 'Edit', edit_team_event_path(@team,event) %></td>
              <td><%= link_to 'Show', team_event_path(@team,event) %></td>
              <td><%= link_to 'Destroy', [@team,event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
<td>Aguardando aprovação</td>

              <% if current_user.person.turma == @team %>
                  <%= form_tag("/teams/#{@team.id}/events/#{event.id}", method: 'get') do %>
                    <td><div class="form-group" id="btn_agendar">
                      <button <%= submit_tag "Aprovar" , :name => 'status' , :value => true %>Aprovar</button>                    </div></td>
                  <% end %>

              <%end%>


        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', [@team,@event] %> |
<%= link_to 'Back', [@team,@event] %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<%= link_to 'Agendar monitoria ', new_event_path %>

<table>
  <thead>
    <tr>
      <th>Turma</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th>Local</th>
      <th>Monitor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @events.each do |event| %>
      <tr>
        <td><%= event.team %></td>
        <td><%= event.inicio %></td>
        <td><%= event.fim %></td>
        <td><%= event.local %></td>
        <td><%= event.team.monitor %></td>
        
        <td><%= link_to 'Show', event %></td>
        <% if current_user.person == event.team.monitor %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<%= " Total de horas de monitoria: #{@cont} " %>
<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', team_path(@team) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Turma:</strong>
  <%= @event.team.descricao %>
</p>
<p>
  <strong>Monitoria:</strong>
  <%=@event.descricao %>
</p>

<p>
  <strong>Data:</strong>
  <%= I18n.l(@event.inicio) %>
</p>
<p>
  <strong>Hora:</strong>
  13:45 h
</p>

<p>
  <strong>Local:</strong>
  <%= @event.local %>
</p>

<table>
  <thead>
    <tr>
      <th>Participantes confirmados</th>
    </tr>
  </thead>

  <tbody>
    <% @event.people.each do |p| %>
      <tr>
        <td><%= p.nome %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% @person = false %>
<% @event.people.each do |p| %>
  <% if current_user.person == p %>
    <% @person = true %>
  <% end %>
<% end %>

<h2>Avaliações</h2>
<%if !@event.evaluations.empty?%>
  <h3>Média: <%=@event.media%></h3>
<%end%>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Comentário</th>
      <th scope="col">Nota</th>
    </tr>
  </thead>

  <tbody>
    <% @event.evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.comentario %></td>
        <td><%= evaluation.nota %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if @person == true %>
<%= form_tag new_evaluation_path, :method => 'get' do %>
   <div class="form-group">
     <button <%= submit_tag "Avaliar Monitoria" , :name => 'monitoria' , value: @event.id %>Avaliar Monitoria</button>
   </div>
<% end %>
<% end %>
<br><br>
<% if current_user.person.coordenador? %>
  <%= link_to 'Edit', edit_team_event_path(@team,@event) %> |
<%end%>
<%= link_to 'Back', team_path(@team) %>